server:
  port: 8080

spring:
  application:
    name:   usermanagement
  datasource:
#    driver-class-name:  com.mysql.jdbc.Driver
    url:    jdbc:mysql://localhost:3306/usermanagement
    username:   myuser
    password:   mypassword
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect